version: "3.8"

services:
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/graphiti_password_123
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - graphiti-network

  graphiti:
    build:
      context: ..
      dockerfile: ./docker/graphiti/Dockerfile
    container_name: graphiti
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MODEL_NAME: gpt-4o-mini
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: graphiti_password_123
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
    ports:
      - "10001:8001"
    depends_on:
      neo4j:
        condition: service_started
    networks:
      - graphiti-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  graphiti-network:
    driver: bridge
